spring.application.name=securitysite
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/securitysite_db
spring.datasource.username=postgres
spring.datasource.password=qwerty

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mySuperSecretKeyForJwt123456789
jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trendprice.kz@gmail.com
spring.mail.password=cnuncmsrhnkrvbxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=http://localhost:5174