package com.trendprice.securitysite.auth;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class MailService {

    private static final Logger log = LoggerFactory.getLogger(MailService.class);

    private final LocalMailMessageRepository localMailRepository;

    public MailService(LocalMailMessageRepository localMailRepository) {
        this.localMailRepository = localMailRepository;
    }

    public LocalMailMessage sendVerificationEmail(String to, String username, String verificationLink) {
        String subject = "Confirm your email";
        String body = "Hi, " + username + "!\n\n" +
                "Please confirm your email by opening the link below:\n" +
                verificationLink + "\n\n" +
                "This message was generated by the local standalone mailbox. No external email service was used.";

        return saveLocalMessage(to, subject, body);
    }

    public LocalMailMessage sendPasswordResetEmail(String to, String username, String resetLink) {
        String subject = "Reset your password";
        String body = "Hi, " + username + "!\n\n" +
                "Use this link to reset your password:\n" +
                resetLink + "\n\n" +
                "This message was generated by the local standalone mailbox. No external email service was used.";

        return saveLocalMessage(to, subject, body);
    }

    private LocalMailMessage saveLocalMessage(String to, String subject, String body) {
        LocalMailMessage savedMessage = localMailRepository.save(new LocalMailMessage(
                to.trim().toLowerCase(),
                subject,
                body
        ));

        log.info("Local email saved for {} with subject '{}'\n{}", to, subject, body);

        return savedMessage;
    }
}